apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: vault
spec:
  type: secretstores.hashicorp.vault
  version: v1
  metadata:
  - name: vaultAddr
    value: "http://vault:8200"
    # Do not verify TLS
  - name: skipVerify
    value : "false"
  - name: vaultToken 
    value : "roottoken"