version: '3'
services:
  ############################
  # Frontend
  ############################
  command-frontend:
    image: dockerutils/command-frontend
    #build: ../implementations/command-frontend
    ports:
      - "8089:80"
    environment:
      - COMMAND_API_HOST=command-api
    depends_on:
      - redis
    networks:
      - hello-dapr

  ############################
  # Command API
  ############################
  command-api:
    image: dockerutils/command-api
    #build: ../implementations/command-api
    networks:
      - hello-dapr
    environment: 
     - PUB_URL=http://localhost:3500/v1.0/publish/order-pub-sub/orders
    depends_on:
      - redis
  command-api-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "command-api",
     "-app-port", "80",
     "-dapr-grpc-port", "50002",
     "-components-path", "/components"]
    volumes:
        - "./components/:/components"
    depends_on:
      - command-api
    network_mode: "service:command-api"


  ############################
  # Order Processing
  ############################
  order-processing:
    image: dockerutils/order-processing
    #build: ../implementations/order-processing
    depends_on:
      - redis
    environment:
      - STOCK_MANAGER_INVOKE_URL=http://localhost:3500/v1.0/invoke/stock-manager/method/stock
      - RECEIPT_GEN_INVOKE_URL=http://localhost:3500/v1.0/invoke/receipt-generator/method/
    networks:
      - hello-dapr
  order-processing-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "order-processing",
     "-app-port", "8080",
     "-dapr-grpc-port", "50002",
     "-components-path", "/components"]
    volumes:
        - "./components/:/components"
    depends_on:
      - order-processing
    network_mode: "service:order-processing"


  ############################
  # Stock Manager
  ############################
  stock-manager:
    image: dockerutils/stock-manager
    #build: ../implementations/stock-manager
    depends_on:
      - redis
    networks:
      - hello-dapr
  stock-manager-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "stock-manager",
     "-app-port", "8081",
     "-dapr-grpc-port", "50002",
     "-components-path", "/components"]
    volumes:
        - "./components/:/components"
    depends_on:
      - stock-manager
    network_mode: "service:stock-manager"


  ############################
  # Receipt Generator
  ############################
  receipt-generator:
    image: dockerutils/receipt-generator
    #build: ../implementations/receipt-generator
    depends_on:
      - redis
    networks:
      - hello-dapr
    environment:
      - RUST_LOG=debug
  receipt-generator-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "receipt-generator",
     "-app-port", "8081",
     "-dapr-grpc-port", "50002",
     "-components-path", "/components"]
    volumes:
        - "./components/:/components"
    depends_on:
      - receipt-generator
    network_mode: "service:receipt-generator"


  ############################
  # Redis state stores
  ############################
  redis:
    image: "redis:alpine"
    networks:
      - hello-dapr

  # mongo:
  #   image: mongo
  #   networks:
  #     - hello-dapr
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example

networks:
    hello-dapr:
