services:
  ############################
  # Frontend
  ############################
  command-frontend:
    image: dockerutils/command-frontend
    ports:
      - "8089:80"
    environment:
      - COMMAND_API_HOST=command-api

  ############################
  # Command API
  ############################
  command-api:
    image: dockerutils/command-api
    environment: 
     - PUB_URL=http://localhost:3500/v1.0/publish/order-pub-sub/orders
  command-api-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "command-api",
     "-app-port", "80",
     "-log-level", "warn",
     "-components-path", "/components"]
    volumes:
        - "./components/:/components"
    network_mode: "service:command-api"


  ############################
  # Order Processing
  ############################
  order-processing:
    image: dockerutils/order-processing
    environment:
      - STOCK_MANAGER_INVOKE_URL=http://localhost:3500/v1.0/invoke/stock-manager/method/stock
      - RECEIPT_GEN_INVOKE_URL=http://localhost:3500/v1.0/invoke/receipt-generator/method/
  order-processing-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "order-processing",
     "-app-port", "8080",
     "-log-level", "warn",
     "-components-path", "/components"]
    volumes:
        - "./components/:/components"
    network_mode: "service:order-processing"


  ############################
  # Stock Manager
  ############################
  stock-manager:
    image: dockerutils/stock-manager
  stock-manager-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "stock-manager",
     "-app-port", "8081",
     "-log-level", "warn",
     "-components-path", "/components"]
    volumes:
        - "./components/:/components"
    network_mode: "service:stock-manager"


  ############################
  # Receipt Generator
  ############################
  receipt-generator:
    image: dockerutils/receipt-generator
    environment:
      - RUST_LOG=debug
      - MAIL_TO=
      - MAILING_BINDING_URL=
  receipt-generator-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "receipt-generator",
     "-app-port", "8081",
     "-log-level", "warn",
     "-components-path", "/components"]
    volumes:
        - "./components/:/components"
    network_mode: "service:receipt-generator"


  ############################
  # Redis state stores
  ############################
  redis:
    image: "redis:alpine"