services:
  ############################
  # Node app + Dapr sidecar
  ############################
  nodeapp:
    build: ./node
  nodeapp-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "nodeapp",
     "-app-port", "3000",
     "-log-level", "warn",
     "-components-path", "/components"]
    volumes:
        - "./components/:/components:ro"
    network_mode: "service:nodeapp"
  ############################
  # Python app + Dapr sidecar
  ############################
  pythonapp:
    build: ./python
  pythonapp-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
    "-app-id", "pythonapp",
    "-log-level", "warn",
     "-components-path", "/components"]
    volumes:
      - "./components/:/components:ro"
    network_mode: "service:pythonapp"
  ############################
  # Redis state stores
  ############################
  redis:
    image: "redis:alpine"

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example