services:
  ##############
  # Node app
  ##############
  nodeapp:
    build: ./node
    environment:
      - REDIS_HOST=redis
      - REDIS_COLLECTION=statestore
    ports:
      - "50002:50002"
    depends_on:
      - redis
  ##############
  # Python app 
  ##############
  pythonapp:
    build: ./python
    environment:
      - STATE_API_BASE_URL=http://nodeapp:3000
    depends_on:
      - redis
  ##############
  # State store
  ##############
  redis:
    image: "redis:alpine"
