# Snippet réutilisable permettant à un service d'utiliser
# Fluentd comme logging driver
x-log: 
      &fluentd
      driver: "fluentd"
      options:
        fluentd-address: host.docker.internal:24224
        tag: httpd.access


services:
  ############################
  # Frontend
  ############################
  command-frontend:
    image: dockerutils/command-frontend
    ports:
      - "8089:80"
    environment:
      - COMMAND_API_HOST=command-api
  ############################
  # Command API
  ############################
  command-api:
    image: dockerutils/command-api
    links:
      - "fluentd"
    environment: 
     - PUB_URL=http://localhost:3500/v1.0/publish/order-pub-sub/orders
    logging: *fluentd
  command-api-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "command-api",
     "-app-port", "80",
     "-log-as-json", "true",
     "-log-level", "warn",
     "-config", "/config/tracing-config.yml",
     "-components-path", "/components"]
    volumes:
        - "./components/:/components"
        - "./config/:/config"
    depends_on:
      - fluentd
    network_mode: "service:command-api"
    logging: *fluentd


  ############################
  # Order Processing
  ############################
  order-processing:
    image: dockerutils/order-processing
    links:
      - "fluentd"
    environment:
      - STOCK_MANAGER_INVOKE_URL=http://localhost:3500/v1.0/invoke/stock-manager/method/stock
      - RECEIPT_GEN_INVOKE_URL=http://localhost:3500/v1.0/invoke/receipt-generator/method/
    logging: *fluentd
  order-processing-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "order-processing",
     "-app-port", "8080",
     "-log-as-json", "true",
     "-log-level", "warn",
     "-config", "/config/tracing-config.yml",
     "-components-path", "/components"]
    volumes:
        - "./components/:/components"
        - "./config/:/config"
    depends_on:
      - fluentd
    network_mode: "service:order-processing"
    logging: *fluentd


  ############################
  # Stock Manager
  ############################
  stock-manager:
    image: dockerutils/stock-manager
    links:
     - fluentd
    logging: *fluentd
  stock-manager-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "stock-manager",
     "-app-port", "8081",
     "-log-level", "debug",
     "-log-as-json", "true",
     "-config", "/config/tracing-config.yml",
     "-components-path", "/components"]
    volumes:
        - "./components/:/components"
        - "./config/:/config"
    network_mode: "service:stock-manager"
    logging: *fluentd


  ############################
  # Receipt Generator
  ############################
  receipt-generator:
    image: dockerutils/receipt-generator
    links:
     - fluentd
    environment:
      - RUST_LOG=debug
      - MAIL_TO=
      - MAILING_BINDING_URL=http://localhost:3500/v1.0/bindings/mail
    logging: *fluentd
  receipt-generator-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "receipt-generator",
     "-app-port", "8081",
     "-log-level", "warn",
     "-log-as-json", "true",
     "-config", "/config/tracing-config.yml",
     "-components-path", "/components"]
    volumes:
        - "./components/:/components"
        - "./config/:/config"
    depends_on:
      - fluentd
    network_mode: "service:receipt-generator"
    logging: *fluentd

  ############################
  # Redis state stores
  ############################
  redis:
    image: "redis:alpine"

  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch:8.2.3
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    ports:
      - "9200:9200"

  kibana:
    image: kibana:8.2.3
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
