services:
  ############################
  # Frontend
  ############################
  command-frontend:
    image: dockerutils/command-frontend
    ports:
      - "8089:80"
    environment:
      - COMMAND_API_HOST=command-api

  ############################
  # Command API
  ############################
  command-api:
    image: dockerutils/command-api
    environment: 
     - PUB_URL=
  command-api-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "command-api",
     "-app-port", "80",
     "-log-level", "warn",
     "-components-path", "/components"]
    volumes:
        - "./components/:/components"
    network_mode: "service:command-api"


  ############################
  # Order Processing
  ############################
  order-processing:
    image: dockerutils/order-processing
  order-processing-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "order-processing",
     "-app-port", "8080",
     "-log-level", "warn",
     "-components-path", "/components"]
    volumes:
        - "./components/:/components"
    network_mode: "service:order-processing"

  ############################
  # Redis state stores
  ############################
  redis:
    image: "redis:alpine"