services:
  ############################
  # Frontend
  ############################
  command-frontend:
    image: dockerutils/command-frontend
    ports:
      - "8089:80"
    environment:
      - COMMAND_API_HOST=command-api
    depends_on:
      - redis
  ############################
  # Receipt Generator
  ############################
  receipt-generator:
    image: dockerutils/receipt-generator
    depends_on:
      - redis
    environment:
      - RUST_LOG=debug
      - MAIL_TO=
      - MAILING_BINDING_URL=http://localhost:3500/v1.0/bindings/mail
  receipt-generator-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "receipt-generator",
     "-app-port", "8081",
     "-log-level", "warn",
     "-components-path", "/components"]
    volumes:
        - "./components/:/components"
    depends_on:
      vault-init:
        condition: service_completed_successfully
    network_mode: "service:receipt-generator"

  ############################
  # Hashicorp Vault
  ############################
  vault:
    image: vault:latest
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=roottoken
      - VAULT_DEV_LISTEN_ADDR=http://127.0.0.1:8200
      - VAULT_API_ADDR=http://127.0.0.1:8200
    cap_add:
      # Cette capacité permet au coffre-fort d'empêcher ses
      # pages de RAM d'être stockées sur le disque
      - IPC_LOCK
    # healthcheck:
    #   test: ["CMD", "wget", "--spider", "--proxy", "off", http://127.0.0.1:8200/v1/sys/health"]
    #   interval: 5s
    #   timeout: 30s
    #   retries: 5 
    #   start_period: 5s  

  # Initialisation des secrets du Vault
  # (Le faire de cette manière en dehors d'un workshop
  # fait perdre tout son intérêt au Vault)
  vault-init:
    image: vault:latest
    command:
      - /bin/ash
      - -c
      - |
        sleep 5
        vault kv put -mount=secret dapr/redis REDIS_PASS=suchStrongP4ssword!!
    environment:
      - VAULT_TOKEN=roottoken
      - VAULT_ADDR=http://127.0.0.1:8200
    depends_on:
      - vault
    network_mode: "service:vault"

  ############################
  # Redis state stores
  ############################
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass suchStrongP4ssword!!
    depends_on:
      - vault-init
