on: [ push ]
name: Build and Push Receipt generator service to ACR

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v1

      - name: 'Login to ACR'
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: 'Login to Dockerhub'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: "Build and push"
        uses: docker/build-push-action@v3
        with:
          context: ./src/Lab2/implementations/receipt-generator
          push: true
          tags: |
            ${{ secrets.REGISTRY_LOGIN_SERVER }}/receipt-generator:latest
            dockerutils/receipt-generator:latest