name:  Build workshop guide static site and upload it on a blob 

on:
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.6'

    - run: gem update --system

    - run: gem install jekyll 

    - run: jekyll build
      working-directory: ./instructions
 
    - uses: tibor19/static-website-deploy@v1
      with:
        enabled-static-website: 'true'
        folder: 'instructions/_site'
        connection-string: ${{ secrets.STATIC_WEBSITE_CONNECTION_STRING }}
