on: [ push ]
name: Build and Push Command Frontend service to ACR

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v1

      - name: 'Login to ACR'
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: "Build and push"
        uses: docker/build-push-action@v3
        with:
          context: ./src/Lab2/implementations/command-frontend
          push: true
          tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/command-frontend:latest